backend:
  name: test
  branch: master

media_folder: resources/nuxt/static/images
public_folder: /images

collections:
  - label: 'General'
    name: 'general'
    format: 'json'
    delete: false
    files:
      - label: 'Home'
        name: 'home'
        file: 'resources/nuxt/assets/content/home.json'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }