backend:
  name: test
media_folder: resources/nuxt/static/images
public_folder: /images

collections:

  #
  # GENERAL PAGES #######################################################
  #
  - label: 'General'
    name: 'general'
    format: 'json'
    delete: false
    files:
      - label: 'Home'
        name: 'home'
        file: 'resources/nuxt/assets/content/home.json'
        fields:
          - { label: 'Title', name: 'test_tile', widget: 'string' }
          - { label: 'Body', name: 'test_body', widget: 'markdown' }